services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    working_dir: /workspace

    volumes:
      - .:/workspace

    command: >
      bash -c
      "cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Debug &&
       cmake --build build"